### ISSUE TITLE
ModuleNotFoundError webapp, app, httpx, yaml

### ISSUE THREAD

**Issue by eisenheimjelid** [davidalami/VulnMapAI#7]
**Describe the bug**
I followed the instructions to try to test the project. Still, after running the container, I had an error `ModuleNotFoundError` in multiple ways with a different behavior but with the same error message with different modules (packages).

**To Reproduce**
1. Go to https://github.com/davidalami/VulnMapAI#for-developers and follow the instructions. So, I obtained the following result:
```
~/Projects/random/VulnMapAI$ docker run -it --entrypoint=/bin/bash -e "OPENAI_API_KEY=sk-..."  -p 1337:1337 vulnmapai
┌──(root㉿a61403c272a3)-[/app]
└─# python main.py 127.0.0.1 --top_ports 500
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from webapp.app import app
ModuleNotFoundError: No module named 'webapp'
```
2. Go to https://github.com/davidalami/VulnMapAI#for-hackers and follow the instructions. So, I obtained the following result:
```
~/Projects/random/VulnMapAI$ docker run -it \
    -e  OPENAI_API_KEY="sk-..." \
     -v $(pwd):/app \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --cap-add NET_ADMIN \
    --cap-add SYS_MODULE \
    --device /dev/net/tun:/dev/net/tun \
    --entrypoint=/bin/bash -p 1337:1337 quantumcrack/vulnmapai-final:latest
Unable to find image 'quantumcrack/vulnmapai-final:latest' locally
latest: Pulling from quantumcrack/vulnmapai-final
3e359b41b521: Already exists 
2cf2f5b97457: Already exists 
37747e89ab88: Already exists 
c1c542d2f90a: Already exists 
abba38decc9b: Already exists 
50794d3b2d7d: Pull complete 
c42da0915d5a: Pull complete 
e2492b34a12e: Pull complete 
6dc55ac30eeb: Pull complete 
4c4ee7a2bd05: Pull complete 
3128b91b3dba: Pull complete 
e4284cca2e5f: Pull complete 
013d065c4a87: Pull complete 
08d38134aeaa: Pull complete 
c6970020f28e: Pull complete 
17bb70cd13b3: Pull complete 
045ed9306eb8: Pull complete 
Digest: sha256:56f41a1264b20db89a42ca3a45f4efbe6b24eb31f68137ba88f6526db8e201db
Status: Downloaded newer image for quantumcrack/vulnmapai-final:latest
┌──(root㉿df22aafac18c)-[/app]
└─# python main.py 127.0.0.1 --top_ports 500
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from orchestration.pentest import PenetrationTester
  File "/app/orchestration/pentest.py", line 3, in <module>
    from advising.llm import Advisor
  File "/app/advising/llm.py", line 4, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
```

**Expected behavior**
I should see the project running well in my http://localhost:1337 and start test the project to discover possible vulnerabilities into my local network interfaces.

**Screenshots**
![image](https://github.com/davidalami/VulnMapAI/assets/505999/3348989c-dbdc-4b61-88b1-17a60a34cd50)

**Desktop (please complete the following information):**
 - OS: `Linux davtop 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Docker version 24.0.6, build ed223bc
 - I used the [code until the last commit](https://github.com/davidalami/VulnMapAI/commit/76e9a1250cec893019c2a067c77e10bc67b1447e)

**Additional context**
Nothing

**Comment by davidalami** [comment]
Hi @eisenheimjelid !

Firstly, thank you for the detailed bug report and taking the time to test out the project. I sincerely apologize for the inconvenience caused.

Upon investigating, I have identified the issues:

1.  For the "for developers" version: The error was due to the omission of the webapp folder in the Docker image. This is why you received the ModuleNotFoundError: No module named 'webapp'.
2.  For the "for hackers" version: The Docker image quantumcrack/vulnmapai-final:latest had not been updated with the latest changes which caused the second ModuleNotFoundError: No module named 'yaml'.

I have now fixed both these issues:

1. The Docker image for the "for developers" version now includes the webapp folder.
2. I've pushed an updated version of the Docker image for the "for hackers" version.

Please pull the latest Docker images and retry the steps you followed. It should now work as expected. If you run into any other issues or have further questions, please don't hesitate to let me know.

Again, I appreciate your patience and support. Thank you for helping make this project better.

Cheers!

**Comment by davidlorius** [comment]
Thank you so much!! now is working :sunglasses:

**Comment by davidlorius** [comment]
Fixed with :pray: 

* https://github.com/davidalami/VulnMapAI/commit/2e0ccbf87510573d464d1c7aaf9568de2525925a
* https://github.com/davidalami/VulnMapAI/commit/99890c73cd7248b37fbce52939c96f1d9bd745e5
